version: '3'
services:
  db:
    image: mysql:8.0.25
    ports:
       - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypasswd
      - MYSQL_DATABASE=root
    volumes:
      - volume=/root/docker/[container_name]/conf.d:/etc/mysql/conf.d \mysql

